#!/bin/bash

GO_VERSION="$(grep '^toolchain' $INPUT_MODFILE | sed 's/toolchain go*//')"
if [ -z "$GO_VERSION" ]; then
    GO_VERSION="$(grep '^go' $INPUT_MODFILE | awk '{ print $2 }')";
fi

echo "GO_VERSION=$GO_VERSION"
