#!/bin/bash

GO_VERSION="$(grep '^toolchain' go.mod | sed 's/toolchain go*//')"
if [ -z "$GO_VERSION" ]; then
    GO_VERSION="$(grep '^go' go.mod | awk '{ print $2 }')";
fi

echo "GO_VERSION=$GO_VERSION"
